### ISSUE TITLE
What modifcations/compromises would be required to make the ATU also work  in the 4m band ? 

### ISSUE THREAD

**Issue by satfan52** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#70]
Hello,

I use an horizontal loop antenna (40M perimeter) that resonates quite well on all ham bands which are a multiple of 7 Mhz so covering the 6M and 4M band as well.  This antenna works beautifully on all bands including in the 6m one. Unfortunately, due to stray caps the resonance shifts below 70 Mhz  so the VSWR is not so good at 70 Mhz (even with a 1-4 ballun).   

The ATU-100/ATU-1000 are specified to work up to the 6M band but I wonder if it would be possible to make some changes so these two models could also be used in the 4M band (with some compromises of course)

I have recently experimented with tandem match couplers of the same type than the ones used in the ATU100/1000 and I was able to get  a good coupler "directivity" between 1.6 Mhz and 145 Mhz using binocular cores of a medium size and a limited numbers of turns on the two secondaries, so I know for sure that adequate tandem couplers could do the job from 1.6 Mhz to 70 Mhz and would not be the bottleneck. 

Regards
Peter

**Comment by sbridger** [comment]
A simple option would be to add a bypass relay around the ATU, connect it's coil to 12V, so that if the ATU is not powered, the bypass relay is straight through, if the ATU is powered, then the ATU is in circuit.

Another option would be to put a current sense diode, R and PNP in the +12V to the relays. if any relay is activated, (i.e. tuner is inline) then the bypass relay is energised, and tuner is inline. If all relays are off, bypass relay is deenergised, tuner is bypassed.

---

Personally  I plan to use the ATU at the antenna (mast head), and I want to have multiple antenna switches there, including a coax VHF/UHF select.

An I2C output to select more relays would work well for me.
